sudo: required

language: javascript

services:
  - docker

before_install:
- docker build -t exitnode .

script:
- docker run --privileged -it -e PUBLIC_IP=0.0.0.0 exitnode timeout −−preserve−status 60 ./build/docker/docker-cmd
